#!/bin/sh

set -e

COMMAND="$1"
shift || true
APP_CONTAINER="app"
PROFILES=""

for ARG in "$@"; do
  case "$ARG" in
    --pgsql)
      PROFILES="$PROFILES --profile pgsql"
      ;;
    --meilisearch)
      PROFILES="$PROFILES --profile meilisearch"
      ;;
  esac
done

case "$COMMAND" in
  build)
    echo "Setting up environment..."
    cp -n .env.example .env || echo ".env already exists."
    docker compose $PROFILES build
    docker compose $PROFILES up -d
    docker compose exec $APP_CONTAINER composer install
    docker compose exec $APP_CONTAINER php artisan key:generate
    docker compose exec $APP_CONTAINER npm install
    docker compose exec $APP_CONTAINER npm run build
    docker compose exec $APP_CONTAINER php artisan migrate:fresh --force
    ;;
  up)
    echo "Starting containers..."
    docker compose $PROFILES up -d
    ;;
  down)
    echo "Stopping containers..."
    docker compose $PROFILES down
    ;;
  workspace)
    echo "Accessing app container..."
    docker compose exec $APP_CONTAINER bash -i
    ;;
  *)
    echo "Usage: $0 {build|up|down|workspace} [--pgsql] [--meilisearch]"
    exit 1
    ;;
esac
